// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef INT128_PARAM_TRAITS_SPECIALIZATIONS_HPP
#define INT128_PARAM_TRAITS_SPECIALIZATIONS_HPP

/**
 * @file int128_param_traits_specializations.hpp
 * @brief Type traits para int128_param_t (TC, MS, EK) en el namespace nstd::
 *
 * @section why_nstd ¿Por qué nstd:: en lugar de std::?
 *
 * El estándar C++ **prohíbe** especializar templates en el namespace `std::`
 * para tipos definidos por el usuario, excepto en casos muy limitados.
 * MSVC y libc++ aplican esta restricción estrictamente.
 *
 * Por ello, esta biblioteca define sus traits en el namespace `nstd::` (new std).
 * El namespace `nstd::` replica la API de `std::` exactamente:
 *
 * @code
 * // ❌ INCORRECTO - no funciona en MSVC/libc++:
 * std::is_integral_v<uint128_tc_t>           // → false
 * std::numeric_limits<uint128_tc_t>::digits  // → 0
 *
 * // ✅ CORRECTO - usar nstd:: para tipos int128:
 * nstd::is_integral_v<uint128_tc_t>          // → true
 * nstd::numeric_limits<uint128_tc_t>::digits // → 128
 * @endcode
 *
 * @section phase175_types Phase 1.75 Types
 *
 * Esta biblioteca soporta 6 tipos int128 (3 representaciones × 2 signedness):
 *
 * **Two's Complement (TC):**
 * - uint128_tc_t (unsigned)
 * - int128_tc_t (signed)
 *
 * **Magnitude-Sign (MS):**
 * - uint128_ms_t (unsigned)
 * - int128_ms_t (signed)
 *
 * **Excess-K (EK):**
 * - uint128_ek_t (unsigned)
 * - int128_ek_t (signed)
 *
 * **Default aliases (backward compatible):**
 * - uint128_t = uint128_tc_t
 * - int128_t = int128_tc_t
 *
 * @section usage Uso recomendado
 *
 * @code
 * #include "int128_param_traits_specializations.hpp"
 *
 * // Traits para int128 (usar nstd::)
 * static_assert(nstd::is_integral_v<uint128_tc_t>);
 * static_assert(nstd::is_unsigned_v<uint128_ms_t>);
 * static_assert(nstd::is_signed_v<int128_ek_t>);
 *
 * // Traits para tipos builtin (nstd:: delega a std::)
 * static_assert(nstd::is_integral_v<int>);     // funciona igual que std::
 * static_assert(nstd::is_integral_v<uint64_t>); // funciona igual que std::
 * @endcode
 *
 * @warning Este header debe incluirse ANTES de usar traits con int128_param_t.
 *
 * @author Julián Calderón Almendros <julian.calderon.almendros@gmail.com>
 * @version 1.75.0
 * @date 2026-02-03
 * @copyright Boost Software License 1.0
 */

// Detectar si las especializaciones de traits están disponibles
#if defined(_LIBCPP_VERSION)
#define UINT128_USING_LIBCPP 1
#elif defined(_MSC_VER) && !defined(__INTEL_LLVM_COMPILER)
#define UINT128_USING_LIBCPP 1
#elif defined(__INTEL_LLVM_COMPILER) && defined(_MSC_VER)
#define UINT128_USING_LIBCPP 1
#else
#define UINT128_USING_LIBCPP 0
#endif

// ⚠️ IMPORTANT: Include type_traits HERE, before the specializations
#include <type_traits>

namespace nstd
{
    // Forward declarations are handled by int128_parameterized.hpp
    // Type aliases defined there:
    // - uint128_tc_t, int128_tc_t
    // - uint128_ms_t, int128_ms_t
    // - uint128_ek_t, int128_ek_t
    // - uint128_t, int128_t (default to TC)

    // ===============================================================================
    // TYPE TRAITS FUNDAMENTALES (1 PARÁMETRO)
    // ===============================================================================

#if !UINT128_USING_LIBCPP

    // Templates base que heredan de std::
    template <typename T>
    struct is_integral : std::is_integral<T>
    {
    };

    template <typename T>
    struct is_arithmetic : std::is_arithmetic<T>
    {
    };

    template <typename T>
    struct is_unsigned : std::is_unsigned<T>
    {
    };

    template <typename T>
    struct is_signed : std::is_signed<T>
    {
    };

    template <typename T>
    struct is_trivially_copyable : std::is_trivially_copyable<T>
    {
    };

    template <typename T>
    struct is_trivially_constructible : std::is_trivially_constructible<T>
    {
    };

    template <typename T>
    struct is_trivially_default_constructible : std::is_trivially_default_constructible<T>
    {
    };

    template <typename T>
    struct is_trivially_copy_constructible : std::is_trivially_copy_constructible<T>
    {
    };

    template <typename T>
    struct is_trivially_move_constructible : std::is_trivially_move_constructible<T>
    {
    };

    template <typename T>
    struct is_trivially_copy_assignable : std::is_trivially_copy_assignable<T>
    {
    };

    template <typename T>
    struct is_trivially_move_assignable : std::is_trivially_move_assignable<T>
    {
    };

    template <typename T>
    struct is_trivially_destructible : std::is_trivially_destructible<T>
    {
    };

    template <typename T>
    struct is_standard_layout : std::is_standard_layout<T>
    {
    };

    // ===============================================================================
    // MACRO HELPER: Define specializations for one type
    // ===============================================================================

// Variadic macro to handle types with commas (e.g., int128_param_t<S, F>)
#define NSTD_DEFINE_INT128_TRAITS(IS_SIGNED, ...)                                                    \
    template <>                                                                                      \
    struct is_integral<__VA_ARGS__> : std::true_type                                                 \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_arithmetic<__VA_ARGS__> : std::true_type                                               \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_unsigned<__VA_ARGS__> : std::conditional_t<IS_SIGNED, std::false_type, std::true_type> \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_signed<__VA_ARGS__> : std::conditional_t<IS_SIGNED, std::true_type, std::false_type>   \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_copyable<__VA_ARGS__> : std::true_type                                       \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_constructible<__VA_ARGS__> : std::true_type                                  \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_default_constructible<__VA_ARGS__> : std::true_type                          \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_copy_constructible<__VA_ARGS__> : std::true_type                             \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_move_constructible<__VA_ARGS__> : std::true_type                             \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_copy_assignable<__VA_ARGS__> : std::true_type                                \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_move_assignable<__VA_ARGS__> : std::true_type                                \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_trivially_destructible<__VA_ARGS__> : std::true_type                                   \
    {                                                                                                \
    };                                                                                               \
    template <>                                                                                      \
    struct is_standard_layout<__VA_ARGS__> : std::true_type                                          \
    {                                                                                                \
    };

    // ===============================================================================
    // ESPECIALIZACIONES PARA LOS 6 TIPOS (TC, MS, EK × unsigned/signed)
    // ===============================================================================

    // Binary Natural (unsigned)
    NSTD_DEFINE_INT128_TRAITS(false, nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>)

    // Two's Complement (signed)
    NSTD_DEFINE_INT128_TRAITS(true, nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>)

    // Magnitude-Sign (signed)
    NSTD_DEFINE_INT128_TRAITS(true, nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::magnitude_sign>)

    // Excess-K (signed)
    NSTD_DEFINE_INT128_TRAITS(true, nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::excess_k>)

#undef NSTD_DEFINE_INT128_TRAITS

    // ===============================================================================
    // TYPE TRAITS DE DOS PARÁMETROS
    // ===============================================================================

    template <typename T, typename U>
    struct is_trivially_assignable : std::is_trivially_assignable<T, U>
    {
    };

// Macro helper for two-parameter traits (variadic)
#define NSTD_DEFINE_INT128_ASSIGNABLE(...)                                              \
    template <>                                                                         \
    struct is_trivially_assignable<__VA_ARGS__ &, __VA_ARGS__> : std::true_type         \
    {                                                                                   \
    };                                                                                  \
    template <>                                                                         \
    struct is_trivially_assignable<__VA_ARGS__ &, const __VA_ARGS__ &> : std::true_type \
    {                                                                                   \
    };                                                                                  \
    template <>                                                                         \
    struct is_trivially_assignable<__VA_ARGS__ &, __VA_ARGS__ &&> : std::true_type      \
    {                                                                                   \
    };                                                                                  \
    template <>                                                                         \
    struct is_trivially_assignable<__VA_ARGS__ &, __VA_ARGS__ &> : std::true_type       \
    {                                                                                   \
    };

    // Apply to all 4 core types: binnat (unsigned), TC/MS/EK (signed)
    NSTD_DEFINE_INT128_ASSIGNABLE(nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>)
    NSTD_DEFINE_INT128_ASSIGNABLE(nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>)
    NSTD_DEFINE_INT128_ASSIGNABLE(nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::magnitude_sign>)
    NSTD_DEFINE_INT128_ASSIGNABLE(nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::excess_k>)

#undef NSTD_DEFINE_INT128_ASSIGNABLE

    // ===============================================================================
    // CONVERSIONES SIGNED/UNSIGNED
    // ===============================================================================

    template <typename T>
    struct make_signed
    {
        using type = std::make_signed_t<T>;
    };

    template <typename T>
    struct make_unsigned
    {
        using type = std::make_unsigned_t<T>;
    };

    // Binary Natural (unsigned) <-> Two's Complement (signed)
    template <>
    struct make_signed<nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>>
    {
        using type = nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>;
    };
    template <>
    struct make_unsigned<nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>>
    {
        using type = nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>;
    };

    // Magnitude-Sign (signed) <-> Binary Natural (unsigned)
    template <>
    struct make_unsigned<nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::magnitude_sign>>
    {
        using type = nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>;
    };

    // Excess-K (signed) <-> Binary Natural (unsigned)
    template <>
    struct make_unsigned<nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::excess_k>>
    {
        using type = nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>;
    };

    // Idempotent operations (signed → signed, unsigned → unsigned)
    template <>
    struct make_signed<nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>>
    {
        using type = nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>;
    };
    template <>
    struct make_signed<nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::magnitude_sign>>
    {
        using type = nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::magnitude_sign>;
    };
    template <>
    struct make_signed<nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::excess_k>>
    {
        using type = nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::excess_k>;
    };
    template <>
    struct make_unsigned<nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>>
    {
        using type = nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>;
    };

    // ===============================================================================
    // HASH
    // ===============================================================================

    template <typename T>
    struct hash;

// Macro helper for hash (variadic)
#define NSTD_DEFINE_INT128_HASH(...)                                  \
    template <>                                                       \
    struct hash<__VA_ARGS__>                                          \
    {                                                                 \
        size_t operator()(const __VA_ARGS__ &value) const noexcept    \
        {                                                             \
            std::hash<uint64_t> hasher;                               \
            return hasher(value.high()) ^ (hasher(value.low()) << 1); \
        }                                                             \
    };

    NSTD_DEFINE_INT128_HASH(nstd::int128_param_t<nstd::signedness::unsigned_type, nstd::representation_form::binnat>)
    NSTD_DEFINE_INT128_HASH(nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::twos_complement>)
    NSTD_DEFINE_INT128_HASH(nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::magnitude_sign>)
    NSTD_DEFINE_INT128_HASH(nstd::int128_param_t<nstd::signedness::signed_type, nstd::representation_form::excess_k>)

#undef NSTD_DEFINE_INT128_HASH

    // ===============================================================================
    // HELPER VARIABLES (C++17)
    // ===============================================================================

    template <typename T>
    inline constexpr bool is_integral_v = is_integral<T>::value;

    template <typename T>
    inline constexpr bool is_arithmetic_v = is_arithmetic<T>::value;

    template <typename T>
    inline constexpr bool is_unsigned_v = is_unsigned<T>::value;

    template <typename T>
    inline constexpr bool is_signed_v = is_signed<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_copyable_v = is_trivially_copyable<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_constructible_v = is_trivially_constructible<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_default_constructible_v = is_trivially_default_constructible<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_copy_constructible_v = is_trivially_copy_constructible<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_move_constructible_v = is_trivially_move_constructible<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_copy_assignable_v = is_trivially_copy_assignable<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_move_assignable_v = is_trivially_move_assignable<T>::value;

    template <typename T>
    inline constexpr bool is_trivially_destructible_v = is_trivially_destructible<T>::value;

    template <typename T>
    inline constexpr bool is_standard_layout_v = is_standard_layout<T>::value;

    template <typename T, typename U>
    inline constexpr bool is_trivially_assignable_v = is_trivially_assignable<T, U>::value;

    // Type aliases
    template <typename T>
    using make_signed_t = typename make_signed<T>::type;

    template <typename T>
    using make_unsigned_t = typename make_unsigned<T>::type;

#endif // !UINT128_USING_LIBCPP

} // namespace nstd

#endif // INT128_PARAM_TRAITS_SPECIALIZATIONS_HPP
